# Generated by Django 4.2.1 on 2023-05-03 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='promotions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.RenameModel(
            old_name='Discount',
            new_name='Promotion',
        ),
        migrations.CreateModel(
            name='PromotionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='posts.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='posts.promotion')),
            ],
        ),
    ]
