# Generated by Django 4.2.1 on 2023-05-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Ф.И.О.:')),
                ('number', models.IntegerField(null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email:')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
